# language: python
language: node_js
node_js:
  - "10.23.2"
branches:
  only: master
# here we need to install all our dependencies to enable the future steps
install:
- pip install --user awscli
- pip install --user aws-sam-cli
script:
- sam validate --template api-template-cf.yaml
- sam build --template-file api-template-cf.yaml

deploy:
  provider: script
  script: sam deploy --config-file sam-api-config.toml --stack-name ElectricityPricesApi
  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_failure: always
env:
  global:
  - AWS_DEFAULT_REGION=ap-southeast-2
  - access_key_id: $AWS_ACCESS_KEY_ID
  - secret_access_key: $AWS_SECRET_ACCESS_KEY