# language: python
language: node_js
node_js:
  - "10.23.2"
branches:
  only: master
# here we need to install all our dependencies to enable the future steps
install:
- pip install --user awscli
- pip install --user aws-sam-cli
script:
- sam validate --template api-template-cf.yaml
# - sam build --template-file api-template-cf.yaml
- sam package --template-file api-template-cf.yaml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-u7y9djooatel --output-template-file serverless-output.yaml

deploy:
  provider: script
  # script: sam deploy --config-file sam-api-config.toml --stack-name ElectricityPricesApi
  script: sam deploy --template-file serverless-output.yaml --stack-name ElectricityPricesApi --capabilities CAPABILITY_IAM --parameter-overrides "S3BucketUrl=\"https://quarterly-survey-of-domestic-electricity-prices.s3-ap-southeast-2.amazonaws.com/public/\""

  skip_cleanup: true
  on:
    branch: master
notifications:
  email:
    on_failure: always
env:
  global:
  - AWS_DEFAULT_REGION=ap-southeast-2
  - access_key_id: $AWS_ACCESS_KEY_ID
  - secret_access_key: $AWS_SECRET_ACCESS_KEY