version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CronFunction"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-u7y9djooatel"
s3_prefix = "CronFunction"
region = "ap-southeast-2"
profile = "pablo-developer"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
parameter_overrides = "MbieURL=\"https://www.mbie.govt.nz\" LinkSearchURL=\"building-and-energy/energy-and-natural-resources/energy-statistics-and-modelling/energy-statistics/energy-prices/electricity-cost-and-price-monitoring/\" S3BucketName=\"quarterly-survey-of-domestic-electricity-prices\""
